export const changeValue = 'changeValue'
export const changeMessageValue = 'changeMessageValue'
export const sendMessage = 'sendMessage'
export const addPost = 'addPost'
export const followToggle = 'followToggle'
export const loadMore = 'loadMore'
export const totalCount = 'totalCount'
export const pageChanger = 'pageChanger'
export const onLoad = 'onLoad'
export const loadProfile = 'loadProfile'
export const authorizing = 'authorizing'
export const followLoading = 'followLoading'
export const getStatus = 'getStatus'

